import { Toaster } from "@/components/ui/sonner";
import { Bricolage_Grotesque } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import "./prosemirror.css";

const sfPro = localFont({
  // weight: ["200", "300", "400", "500", "600", "700", "800"],
  src: "../fonts/SF-Pro.ttf",
  variable: "--font-sf-pro",
  display: "swap",
});

const bricolageGrotesque = Bricolage_Grotesque({
  // weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-bricolage-grotesque",
  display: "swap",
});

export const metadata = {
  title: "TriGardening",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sfPro.variable} ${bricolageGrotesque.variable} text-neutral-800 antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
